# Префикс Ctrl+A
set -g prefix C-a

# Основные настройки 
set -g default-terminal "tmux-256color"
#set -ga terminal-overrides ",xterm-256color:Tc"
set -g allow-passthrough on

# Изменение индексов
set -g base-index 1           # нумерация окон с 1 (не с 0)
set -g pane-base-index 1      # нумерация панелей с 1

set -g mouse on               # мышь: скролл, клик по панелям
set -g renumber-windows on    # перенумеровать окна при закрытии
set -g history-limit 10000    # история команд
set -sg escape-time 0         # убрать задержку после Escape (важно для nvim)
set -g focus-events on        # события фокуса (нужно для nvim)

# Сортировка сессий по имени
bind s choose-tree -sZ -O name

# Горячие клавиши — окна
bind c new-window -c "#{pane_current_path}"   # новое окно в текущей папке
bind , command-prompt "rename-window '%%'"    # переименовать окно

# Горячие клавиши — панели
unbind %
bind-key '\' split-window -h -c "#{pane_current_path}"  # вертикальный split

unbind '"'
bind - split-window -v -c "#{pane_current_path}"  # горизонтальный split

# Перезагрузка конфигурации
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

# Навигация между панелями как в vim
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Изменение размера панелей
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Горячие клавиши — сессии
bind s choose-session         # выбор сессии
bind $ command-prompt "rename-session '%%'"  # переименовать сессию

# Копирование (vi режим)
set -g mode-keys vi
bind Enter copy-mode          # войти в режим копирования
bind -T copy-mode-vi v send -X begin-selection      # выделение как в vim
bind -T copy-mode-vi y send -X copy-selection-and-cancel  # копировать
bind -T copy-mode-vi Escape send -X cancel          # выйти

bind x kill-pane # Закрытие панели без подтверждения

# Плагины (TPM)
set-environment -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.tmux/plugins/"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'   # разумные дефолты
set -g @plugin 'tmux-plugins/tmux-resurrect'  # сохранение сессий
set -g @plugin 'tmux-plugins/tmux-continuum'  # автосохранение сессий

# Настройки плагинов

# Сохранение сессий
set -g @continuum-restore 'on'   # автовосстановление сессий при старте
set -g @resurrect-capture-pane-contents 'on' #  сохраняет содержимое панелей (текст который виден на экране)

# Сессии хранятся тут ~/.local/share/tmux/resurrect
# Для удаления команда rm -rf ~/.local/share/tmux/resurrect

# keys
set -g terminal-overrides "xterm*:smkx@:rmkx@"

# Статус-бар
set -g status-justify centre
set -g status-style bg=default
set -g status-left '#S'
set -g status-right '#H / %d.%m.%Y %H:%M'

# Инициализация TPM (всегда в конце файла)
run '~/.tmux/plugins/tpm/tpm'
